database:
  host: localhost
  port: 5432
  name: myapp

server:
  port: 8080
  host: 0.0.0.0

logging:
  level: info
  format: json

features:
  authentication: true
  caching: false

version: "1.0.0"